USE SCHEMA STAGING;

CREATE OR REPLACE VIEW TRANSACTIONS_CLEAN AS
SELECT
    -- Campos originales
    TRANSACTION_AMOUNT,
    HOUR_OF_DAY,
    DAY_OF_WEEK,
    IS_WEEKEND,
    IS_ONLINE,
    MERCHANT_CATEGORY,
    CUSTOMER_AGE,
    ACCOUNT_AGE_DAYS,
    TRANSACTIONS_LAST_24H,
    AVG_TRANSACTION_AMT,
    AMOUNT_VS_AVG_RATIO,
    DISTANCE_FROM_HOME,
    FAILED_ATTEMPTS,
    IS_FOREIGN_TRANSACTION,
    IS_FRAUD,

    -- Feature: parte del día
    CASE
        WHEN HOUR_OF_DAY BETWEEN 0  AND 5  THEN 'dawn'
        WHEN HOUR_OF_DAY BETWEEN 6  AND 11 THEN 'morning'
        WHEN HOUR_OF_DAY BETWEEN 12 AND 17 THEN 'afternoon'
        WHEN HOUR_OF_DAY BETWEEN 18 AND 23 THEN 'evening'
    END AS TIME_OF_DAY,

    -- Feature: categoría del monto
    CASE
        WHEN TRANSACTION_AMOUNT < 10    THEN 'micro'
        WHEN TRANSACTION_AMOUNT < 50    THEN 'small'
        WHEN TRANSACTION_AMOUNT < 200   THEN 'medium'
        WHEN TRANSACTION_AMOUNT < 1000  THEN 'large'
        ELSE 'very_large'
    END AS AMOUNT_CATEGORY,

    -- Feature: monto escalado
    (TRANSACTION_AMOUNT - AVG(TRANSACTION_AMOUNT) OVER()) /
    NULLIF(STDDEV(TRANSACTION_AMOUNT) OVER(), 0) AS AMOUNT_ZSCORE,

    -- Feature: cliente de riesgo por edad de cuenta
    CASE
        WHEN ACCOUNT_AGE_DAYS < 90   THEN 'new'
        WHEN ACCOUNT_AGE_DAYS < 365  THEN 'recent'
        WHEN ACCOUNT_AGE_DAYS < 1825 THEN 'established'
        ELSE 'veteran'
    END AS ACCOUNT_AGE_CATEGORY,

    -- Label legible
    CASE WHEN IS_FRAUD = 1 THEN 'FRAUD'
         ELSE 'LEGITIMATE' END AS LABEL,

    INGESTION_TS

FROM FRAUD_DETECTION.RAW.TRANSACTIONS
WHERE TRANSACTION_AMOUNT IS NOT NULL
  AND IS_FRAUD IS NOT NULL;
  